# Generated by Django 4.0 on 2022-01-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoint',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
