# Generated by Django 4.0 on 2022-01-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summer', '0002_userpoint_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpoint',
            old_name='department',
            new_name='belong_to',
        ),
    ]
