# Generated by Django 4.0 on 2022-01-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer', '0003_rename_department_userpoint_belong_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
